#pragma once

//типи кнопок голвоного меню
enum MenuButtonType
{
	MENU_BUTTON_NEW_GAME = 0,
	MENU_BUTTON_OPTIONS,
	MENU_BUTTON_HELP,
	MENU_BUTTON_ABOUT,
	MENU_BUTTON_EXIT
};

//вс≥ ≥гров≥ текстури
	enum TextureType
	{
		//кольоров≥ текстури ≥грових ф≥гур
		TEXTURE_BRIDGE_EMPTY = 0,
		TEXTURE_BRIDGE_BLUE,
		TEXTURE_BRIDGE_GREEN,
		TEXTURE_BRIDGE_LIGHT_BLUE,
		TEXTURE_BRIDGE_LIGHT_YELLOW,
		TEXTURE_BRIDGE_ORANGE,
		TEXTURE_BRIDGE_PURPLE,
		TEXTURE_BRIDGE_YELLO,

		//кольоров≥ текстури зменшених ≥грових ф≥гур, €к≥ з€вл€ютьс€ збоку (наступн≥)
		TEXTURE_MINI_BRIDGE_BLUE,
		TEXTURE_MINI_BRIDGE_GREEN,
		TEXTURE_MINI_BRIDGE_LIGHT_BLUE,
		TEXTURE_MINI_BRIDGE_LIGHT_YELLOW,
		TEXTURE_MINI_BRIDGE_ORANGE,
		TEXTURE_MINI_BRIDGE_PURPLE,
		TEXTURE_MINI_BRIDGE_YELLO,

		//фонов≥ текстури ≥грових в≥кон
		TEXTURE_BACKGROUND_GLASS_WND,
		TEXTURE_BACKGROUND_MAIN_WND,
		TEXTURE_BACKGROUND_OPTIONS_WND,
		TEXTURE_BACKGROUND_ABOUT_WND,
		TEXTURE_BACKGROUND_HELP_WND,


		TEXTURE_MENU_BTN_LINE,

		//комбобокс
		TEXTURE_COMBOBOX_CHECKED,
		TEXTURE_COMBOBOX_UNCHECK,

		//текстури партикл≥в
		TEXTURE_PARTICLES
	};


	//вс≥ ≥гров≥ звуков≥ ефекти
	enum SoundEffectType
	{
		SOUND_EFFECT_FIGURE_MOVE = 0,
		SOUND_EFFECT_FIGURE_ROTATE,
		SOUND_EFFECT_FIGURE_DOWN,
		SOUND_EFFECT_LINE_CRASH
	};


	//вс≥ ≥гров≥ шрифти
	enum FontType
	{
		FONT_GLASS_WND_OUTPUTS = 0,
		FONT_MAIN_WND_MENU
	};

	//вс€ фонова музика
	enum BackgroundMusicType
	{
		BACK_MUSIC_HARDCORE = 0,
		BACK_MUSIC_CHILLOUT
	};

	enum WindowType
	{
		//типи в≥кон в гр≥
		WINDOW_MAIN_MENU = 0,
		WINDOW_OPTIONS,
		WINDOW_GLASS,
		WINDOW_HELP,
		WINDOW_ABOUT
	};

	enum FigureColorType
	{
		FIGURE_COLOR_EMPTY = 0,
		FIGURE_COLOR_LIGHT_YELLOW,
		FIGURE_COLOR_GREEN,
		FIGURE_COLOR_ORANGE,
		FIGURE_COLOR_YELLOW,
		FIGURE_COLOR_PURPLE,
		FIGURE_COLOR_BLUE,
		FIGURE_COLOR_LIGHT_BLUE
	};
	
	enum StaticSettingType
	{
		STATIC_SETTING_PLAY_BACKGROUND = 0,
		STATIC_SETTING_PLAY_SOUND_EFFECTS
	};

	enum DynamicSettingType
	{
		DYNAMIC_SETTING_GAME_PAUSED = 0,
		DYNAMIC_SETTING_GAME_OVERED,
		DYNAMIC_SETTING_LAST_PRESSED_BUTTON
	};